 <?php

/*
INSERT INTO `ram_permissions` ( `name`, `value`, `description`, `created_at`, `updated_at`) VALUES ('Index Asistencia', 'view-asistencia-list', 'Ver Listado de Asistencia', '2018-09-19 08:57:19', '2018-09-19 08:57:19');
INSERT INTO `ram_permissions` ( `name`, `value`, `description`, `created_at`, `updated_at`) VALUES ('Crear Asistencia', 'create-asistencia', 'Crear Asistencia Nuevos', '2018-09-19 08:58:33', '2018-09-19 08:58:33');
INSERT INTO `ram_permissions` ( `name`, `value`, `description`, `created_at`, `updated_at`) VALUES ('Ver Asistencia', 'show-asistencia-info', 'Ver Información de Asistencia', '2018-09-19 08:59:31', '2018-09-19 08:59:31');
INSERT INTO `ram_permissions` ( `name`, `value`, `description`, `created_at`, `updated_at`) VALUES ('Actualizar Asistencia', 'update-asistencia-info', 'Actualizar Información de Asistencia', '2018-09-19 09:00:01', '2018-09-19 09:00:01');
INSERT INTO `ram_permissions` ( `name`, `value`, `description`, `created_at`, `updated_at`) VALUES ('Eliminar Asistencia', 'delete-asistencia', 'Eliminar Asistencia', '2018-09-19 09:00:24', '2018-09-19 09:00:24');

*/

 return array(
     'listGroups'         => 'groups-management',
     'newGroupPost'       => 'groups-management',
     'newGroup'           => 'groups-management',
     'deleteGroup'        => 'groups-management',
     'showGroup'          => 'groups-management',
     'putGroup'           => 'groups-management',
     'listUsers'          => 'view-users-list',
     'deleteUsers'        => 'delete-user',
     'newUser'            => 'create-user',
     'newUserPost'        => 'create-user',
     'showUser'           => 'update-user-info',
     'putUser'            => 'update-user-info',
     'putActivateUser'    => 'update-user-info',
     'deleteUserGroup'    => 'user-group-management',
     'addUserGroup'       => 'user-group-management',
     'listPermissions'    => 'permissions-management',
     'deletePermission'   => 'permissions-management',
     'newPermission'      => 'permissions-management',
     'newPermissionPost'  => 'permissions-management',
     'showPermission'     => 'permissions-management',
     'putPermission'      => 'permissions-management',
     'addUserPermission'  => 'permissions-management',
     'addGroupPermission' => 'permissions-management',

     'menuCatalogs' => 'catalogs-management',

     'bancoEspecial'  => 'banco-especial',
     'bancoEspecial2' => 'banco-especial-2',

     'listTipoUnidad'    => 'view-tipounidad-list',
     'newTipoUnidad'     => 'create-tipounidad',
     'newTipoUnidadPost' => 'create-tipounidad',
     'showTipoUnidad'    => 'show-tipounidad-info',
     'putTipoUnidad'     => 'update-tipounidad-info',
     'putTipoUnidadPost' => 'update-tipounidad-info',
     'deleteTipoUnidad'  => 'delete-tipounidad',

     'listRendimiento'    => 'view-rendimiento-list',
     'newRendimiento'     => 'create-rendimiento',
     'newRendimientoPost' => 'create-rendimiento',
     'showRendimiento'    => 'show-rendimiento-info',
     'putRendimiento'     => 'update-rendimiento-info',
     'putRendimientoPost' => 'update-rendimiento-info',
     'deleteRendimiento'  => 'delete-rendimiento',

     'listGasolinera'    => 'view-gasolinera-list',
     'newGasolinera'     => 'create-gasolinera',
     'newGasolineraPost' => 'create-gasolinera',
     'showGasolinera'    => 'show-gasolinera-info',
     'putGasolinera'     => 'update-gasolinera-info',
     'putGasolineraPost' => 'update-gasolinera-info',
     'deleteGasolinera'  => 'delete-gasolinera',

     'listCliente'    => 'view-cliente-list',
     'newCliente'     => 'create-cliente',
     'newClientePost' => 'create-cliente',
     'showCliente'    => 'show-cliente-info',
     'putCliente'     => 'update-cliente-info',
     'putClientePost' => 'update-cliente-info',
     'deleteCliente'  => 'delete-cliente',

     'listCombustible'    => 'view-combustible-list',
     'putCombustiblePost' => 'update-combustible-info',

     'listUnidad'    => 'view-unidad-list',
     'newUnidad'     => 'create-unidad',
     'newUnidadPost' => 'create-unidad',
     'showUnidad'    => 'show-unidad-info',
     'putUnidad'     => 'update-unidad-info',
     'putUnidadPost' => 'update-unidad-info',
     'deleteUnidad'  => 'delete-unidad',

     'listOperador'    => 'view-operador-list',
     'newOperador'     => 'create-operador',
     'newOperadorPost' => 'create-operador',
     'showOperador'    => 'show-operador-info',
     'putOperador'     => 'update-operador-info',
     'putOperadorPost' => 'update-operador-info',
     'deleteOperador'  => 'delete-operador',

     'listRuta'    => 'view-ruta-list',
     'newRuta'     => 'create-ruta',
     'newRutaPost' => 'create-ruta',
     'showRuta'    => 'show-ruta-info',
     'putRuta'     => 'update-ruta-info',
     'putRutaPost' => 'update-ruta-info',
     'deleteRuta'  => 'delete-ruta',

     'listCotizacion'    => 'view-cotizacion-list',
     'newCotizacion'     => 'create-cotizacion',
     'newCotizacionPost' => 'create-cotizacion',
     'showCotizacion'    => 'show-cotizacion-info',
     'showCotizacionPdf' => 'show-cotizacion-info',
     'sendCotizacion'    => 'show-cotizacion-info',
     'putCotizacion'     => 'update-cotizacion-info',
     'putCotizacionPost' => 'update-cotizacion-info',
     'deleteCotizacion'  => 'delete-cotizacion',

     'listCodigo'    => 'view-codigo-list',
     'newCodigoPost' => 'create-codigo',

     'listBanco'    => 'view-banco-list',
     'newBanco'     => 'create-banco',
     'newBancoPost' => 'create-banco',
     'showBanco'    => 'show-banco-info',
     'putBanco'     => 'update-banco-info',
     'putBancoPost' => 'update-banco-info',
     'deleteBanco'  => 'delete-banco',

     'listBancoMov'    => 'view-banco-list',
     'newBancoMov'     => 'create-banco',
     'newBancoMovPost' => 'create-banco',
     'showBancoMov'    => 'show-banco-info',
     'putBancoMov'     => 'update-banco-info',
     'putBancoMovPost' => 'update-banco-info',
     'deleteBancoMov'  => 'delete-banco-esp',

     'listBancoCategoria'    => 'view-banco-list',
     'newBancoCategoria'     => 'create-banco',
     'newBancoCategoriaPost' => 'create-banco',
     'showBancoCategoria'    => 'show-banco-info',
     'putBancoCategoria'     => 'update-banco-info',
     'putBancoCategoriaPost' => 'update-banco-info',
     'deleteBancoCategoria'  => 'delete-banco',

     'listBancoSubCategoria'    => 'view-banco-list',
     'newBancoSubCategoria'     => 'create-banco',
     'newBancoSubCategoriaPost' => 'create-banco',
     'showBancoSubCategoria'    => 'show-banco-info',
     'putBancoSubCategoria'     => 'update-banco-info',
     'putBancoSubCategoriaPost' => 'update-banco-info',
     'deleteBancoSubCategoria'  => 'delete-banco',

     'newBancoPrest'     => 'create-banco',
     'newBancoPrestPost' => 'create-banco',
     'deleteBancoPrest'  => 'delete-banco-esp',

     'listBancoPeriodo'    => 'view-banco-list',
     'listBancoPeriodoPut' => 'view-banco-list',

     'listReporte'            => 'view-reporte-list',
     'showReporte'            => 'view-reporte-list',
     'showPresupuesto'        => 'view-reporte-list',
     'showPrestamos'          => 'view-reporte-list',
     'showSueldos'            => 'view-reporte-list',
     'saveSueldos'            => 'view-reporte-list',
     'operSueldos'            => 'view-reporte-list',
     'showCombustibles'       => 'view-reporte-list',
     'showProveedores'        => 'view-reporte-list',
     'showProveedoresTicket'  => 'view-reporte-list',
     'showProveedoresFactura' => 'view-reporte-list',
     'showFacturas'           => 'view-reporte-list',
     'showDeudas'             => 'view-reporte-list',
     'showUnidadesOperadores' => 'view-reporte-list',
     'showUnidades'           => 'view-reporte-list',


     'listAsignacion'    => 'view-asignacion-list',
     'newAsignacion'     => 'create-asignacion',
     'newAsignacionPost' => 'create-asignacion',
     'showAsignacion'    => 'show-asignacion-info',
     'putAsignacion'     => 'update-asignacion-info',
     'putAsignacionPost' => 'update-asignacion-info',
     'deleteAsignacion'  => 'delete-asignacion',

     'newAsignacionCombustible'        => 'update-asignacion-info',
     'newAsignacionCombustiblePost'    => 'update-asignacion-info',
     'newAsignacionCombustibleEspPost' => 'update-asignacion-info',
     'listCombustibleEsp'              => 'view-asignacion-list',
     'showAsignacionEsp'               => 'show-asignacion-info',
     'deleteAsignacionEsp'             => 'delete-asignacion',
     'deleteAsignacionCom'             => 'delete-asignacion',
     'prueba'                          => 'update-asignacion-info',

     'control.index'   => 'view-reporte-list',
     'control.create'  => 'view-reporte-list',
     'control.store'   => 'view-reporte-list',
     'control.show'    => 'view-reporte-list',
     'control.edit'    => 'view-reporte-list',
     'control.update'  => 'view-reporte-list',
     'control.destroy' => 'view-reporte-list',

     'comprobante_combustible.index'   => 'view-reporte-list',
     'comprobante_combustible.create'  => 'view-reporte-list',
     'comprobante_combustible.store'   => 'view-reporte-list',
     'comprobante_combustible.show'    => 'view-reporte-list',
     'comprobante_combustible.edit'    => 'view-reporte-list',
     'comprobante_combustible.update'  => 'view-reporte-list',
     'comprobante_combustible.destroy' => 'view-reporte-list',

     'gasto.index'   => 'view-reporte-list',
     'gasto.create'  => 'view-reporte-list',
     'gasto.store'   => 'view-reporte-list',
     'gasto.show'    => 'view-reporte-list',
     'gasto.edit'    => 'view-reporte-list',
     'gasto.update'  => 'view-reporte-list',
     'gasto.destroy' => 'view-reporte-list',

     'newBancoPrestSueldo'     => 'view-reporte-list',
     'newBancoPrestSueldoPost' => 'view-reporte-list',
     'listBancoPrestSueldo'    => 'view-reporte-list',

     'apiEditaCliente' => 'view-reporte-list',
     'apiEditaOrigen'  => 'view-reporte-list',
     'apiEditaDestino' => 'view-reporte-list',
     'apiEditaEstatus' => 'view-reporte-list',

     'catalogos.origen.index'   => 'view-origen-list',
     'catalogos.origen.create'  => 'create-origen',
     'catalogos.origen.store'   => 'create-origen',
     'catalogos.origen.show'    => 'show-origen-info',
     'catalogos.origen.edit'    => 'update-origen-info',
     'catalogos.origen.update'  => 'update-origen-info',
     'catalogos.origen.destroy' => 'delete-origen',

     'factura.index'   => 'view-factura-list',
     'factura.create'  => 'create-factura',
     'factura.store'   => 'create-factura',
     'factura.show'    => 'show-factura-info',
     'factura.edit'    => 'update-factura-info',
     'factura.update'  => 'update-factura-info',
     'factura.destroy' => 'delete-factura',

     'facturacontrol.index'   => 'view-facturacontrol-list',
     'facturacontrol.create'  => 'create-facturacontrol',
     'facturacontrol.store'   => 'create-facturacontrol',
     'facturacontrol.show'    => 'show-facturacontrol-info',
     'facturacontrol.edit'    => 'update-facturacontrol-info',
     'facturacontrol.update'  => 'update-facturacontrol-info',
     'facturacontrol.destroy' => 'delete-facturacontrol',

     'combustible.index'   => 'view-comb-list',
     'combustible.create'  => 'create-comb',
     'combustible.store'   => 'create-comb',
     'combustible.show'    => 'show-comb-info',
     'combustible.edit'    => 'update-comb-info',
     'combustible.update'  => 'update-comb-info',
     'combustible.destroy' => 'delete-comb',

     'proveedor.index'   => 'view-proveedor-list',
     'proveedor.create'  => 'create-proveedor',
     'proveedor.store'   => 'create-proveedor',
     'proveedor.show'    => 'show-proveedor-info',
     'proveedor.edit'    => 'update-proveedor-info',
     'proveedor.update'  => 'update-proveedor-info',
     'proveedor.destroy' => 'delete-proveedor',

     'mantenimiento.index'   => 'view-mantenimiento-list',
     'mantenimiento.create'  => 'create-mantenimiento',
     'mantenimiento.store'   => 'create-mantenimiento',
     'mantenimiento.show'    => 'show-mantenimiento-info',
     'mantenimiento.edit'    => 'update-mantenimiento-info',
     'mantenimiento.update'  => 'update-mantenimiento-info',
     'mantenimiento.destroy' => 'delete-mantenimiento',

     'cat_proveedor.index'   => 'view-cat_proveedor-list',
     'cat_proveedor.create'  => 'create-cat_proveedor',
     'cat_proveedor.store'   => 'create-cat_proveedor',
     'cat_proveedor.show'    => 'show-cat_proveedor-info',
     'cat_proveedor.edit'    => 'update-cat_proveedor-info',
     'cat_proveedor.update'  => 'update-cat_proveedor-info',
     'cat_proveedor.destroy' => 'delete-cat_proveedor',

     'bitacora.index'   => 'view-bitacora-list',
     'bitacora.create'  => 'create-bitacora',
     'bitacora.store'   => 'create-bitacora',
     'bitacora.show'    => 'show-bitacora-info',
     'bitacora.edit'    => 'update-bitacora-info',
     'bitacora.update'  => 'update-bitacora-info',
     'bitacora.destroy' => 'delete-bitacora',

     'foraneo.index'   => 'view-foraneo-list',
     'foraneo.create'  => 'create-foraneo',
     'foraneo.store'   => 'create-foraneo',
     'foraneo.show'    => 'show-foraneo-info',
     'foraneo.edit'    => 'update-foraneo-info',
     'foraneo.update'  => 'update-foraneo-info',
     'foraneo.destroy' => 'delete-foraneo',

     'foraneo_operador.index'   => 'view-foraneo_operador-list',
     'foraneo_operador.create'  => 'create-foraneo_operador',
     'foraneo_operador.store'   => 'create-foraneo_operador',
     'foraneo_operador.show'    => 'show-foraneo_operador-info',
     'foraneo_operador.edit'    => 'update-foraneo_operador-info',
     'foraneo_operador.update'  => 'update-foraneo_operador-info',
     'foraneo_operador.destroy' => 'delete-foraneo_operador',

     'showClientesMensual' => 'view-reporte-cliente',

     'menuInventario' => 'menu-inventario',

     'material.index'   => 'view-materiales-list',
     'material.create'  => 'create-materiales',
     'material.store'   => 'create-materiales',
     'material.show'    => 'show-materiales-info',
     'material.edit'    => 'update-materiales-info',
     'material.update'  => 'update-materiales-info',
     'material.destroy' => 'delete-materiales',

     'materialSalida.index'   => 'view-materiales-list',
     'materialSalida.create'  => 'create-materiales',
     'materialSalida.store'   => 'create-materiales',
     'materialSalida.show'    => 'show-materiales-info',
     'materialSalida.edit'    => 'update-materiales-info',
     'materialSalida.update'  => 'update-materiales-info',
     'materialSalida.destroy' => 'delete-materiales',

     'materialEntrada.index'   => 'view-materiales-list',
     'materialEntrada.create'  => 'create-materiales',
     'materialEntrada.store'   => 'create-materiales',
     'materialEntrada.show'    => 'show-materiales-info',
     'materialEntrada.edit'    => 'update-materiales-info',
     'materialEntrada.update'  => 'update-materiales-info',
     'materialEntrada.destroy' => 'delete-materiales',

     'llanta.index'   => 'view-llantas-list',
     'llanta.create'  => 'create-llantas',
     'llanta.store'   => 'create-llantas',
     'llanta.show'    => 'show-llantas-info',
     'llanta.edit'    => 'update-llantas-info',
     'llanta.update'  => 'update-llantas-info',
     'llanta.destroy' => 'delete-llantas',

     'llantaSalida.index'   => 'view-llantas-list',
     'llantaSalida.create'  => 'create-llantas',
     'llantaSalida.store'   => 'create-llantas',
     'llantaSalida.show'    => 'show-llantas-info',
     'llantaSalida.edit'    => 'update-llantas-info',
     'llantaSalida.update'  => 'update-llantas-info',
     'llantaSalida.destroy' => 'delete-llantas',

     'llantaEntrada.index'   => 'view-llantas-list',
     'llantaEntrada.create'  => 'create-llantas',
     'llantaEntrada.store'   => 'create-llantas',
     'llantaEntrada.show'    => 'show-llantas-info',
     'llantaEntrada.edit'    => 'update-llantas-info',
     'llantaEntrada.update'  => 'update-llantas-info',
     'llantaEntrada.destroy' => 'delete-llantas',

     'dieselAutorizado.index'   => 'view-dieselaut-list',
     'dieselAutorizado.create'  => 'create-dieselaut',
     'dieselAutorizado.store'   => 'create-dieselaut',
     'dieselAutorizado.show'    => 'show-dieselaut-info',
     'dieselAutorizado.edit'    => 'update-dieselaut-info',
     'dieselAutorizado.update'  => 'update-dieselaut-info',
     'dieselAutorizado.destroy' => 'delete-dieselaut',

     'sueldoAdmin.index' => 'view-reporte-list',
     'sueldoAdmin.show'  => 'view-reporte-list',

     'asistencia.index'   => 'view-asistencia-list',
     'asistencia.create'  => 'create-asistencia',
     'asistencia.store'   => 'create-asistencia',
     'asistencia.show'    => 'show-asistencia-info',
     'asistencia.edit'    => 'update-asistencia-info',
     'asistencia.update'  => 'update-asistencia-info',
     'asistencia.destroy' => 'delete-asistencia',

     'delete.button' => 'delete-button',

);
